# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addMovieDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addMovieDialog(object):
    def setupUi(self, addMovieDialog):
        addMovieDialog.setObjectName("addMovieDialog")
        addMovieDialog.resize(400, 155)
        addMovieDialog.setMinimumSize(QtCore.QSize(300, 155))
        addMovieDialog.setMaximumSize(QtCore.QSize(16777215, 200))
        self.verticalLayout = QtWidgets.QVBoxLayout(addMovieDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fileSelectGroup = QtWidgets.QFrame(addMovieDialog)
        self.fileSelectGroup.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fileSelectGroup.setFrameShadow(QtWidgets.QFrame.Plain)
        self.fileSelectGroup.setObjectName("fileSelectGroup")
        self.fileSelectHLayout = QtWidgets.QHBoxLayout(self.fileSelectGroup)
        self.fileSelectHLayout.setObjectName("fileSelectHLayout")
        self.filePathLineEdit = QtWidgets.QLineEdit(self.fileSelectGroup)
        self.filePathLineEdit.setObjectName("filePathLineEdit")
        self.fileSelectHLayout.addWidget(self.filePathLineEdit)
        self.browseButton = QtWidgets.QPushButton(self.fileSelectGroup)
        self.browseButton.setObjectName("browseButton")
        self.fileSelectHLayout.addWidget(self.browseButton)
        self.verticalLayout.addWidget(self.fileSelectGroup)
        self.imdbidGroup = QtWidgets.QFrame(addMovieDialog)
        self.imdbidGroup.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.imdbidGroup.setObjectName("imdbidGroup")
        self.imdbIDHLayout = QtWidgets.QHBoxLayout(self.imdbidGroup)
        self.imdbIDHLayout.setObjectName("imdbIDHLayout")
        spacerItem = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.imdbIDHLayout.addItem(spacerItem)
        self.imdbidLabel = QtWidgets.QLabel(self.imdbidGroup)
        self.imdbidLabel.setObjectName("imdbidLabel")
        self.imdbIDHLayout.addWidget(self.imdbidLabel)
        self.imdbidLineEdit = QtWidgets.QLineEdit(self.imdbidGroup)
        self.imdbidLineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.imdbidLineEdit.setObjectName("imdbidLineEdit")
        self.imdbIDHLayout.addWidget(self.imdbidLineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.imdbIDHLayout.addItem(spacerItem1)
        self.checkIdButton = QtWidgets.QPushButton(self.imdbidGroup)
        self.checkIdButton.setObjectName("checkIdButton")
        self.imdbIDHLayout.addWidget(self.checkIdButton)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.imdbIDHLayout.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.imdbidGroup)
        self.buttonBoxGroup = QtWidgets.QFrame(addMovieDialog)
        self.buttonBoxGroup.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.buttonBoxGroup.setObjectName("buttonBoxGroup")
        self.buttonBoxHLayout = QtWidgets.QHBoxLayout(self.buttonBoxGroup)
        self.buttonBoxHLayout.setObjectName("buttonBoxHLayout")
        spacerItem3 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonBoxHLayout.addItem(spacerItem3)
        self.saveButton = QtWidgets.QPushButton(self.buttonBoxGroup)
        self.saveButton.setEnabled(False)
        self.saveButton.setObjectName("saveButton")
        self.buttonBoxHLayout.addWidget(self.saveButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.buttonBoxHLayout.addItem(spacerItem4)
        self.cancelButton = QtWidgets.QPushButton(self.buttonBoxGroup)
        self.cancelButton.setObjectName("cancelButton")
        self.buttonBoxHLayout.addWidget(self.cancelButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonBoxHLayout.addItem(spacerItem5)
        self.verticalLayout.addWidget(self.buttonBoxGroup)

        self.retranslateUi(addMovieDialog)
        self.cancelButton.clicked.connect(addMovieDialog.reject) # type: ignore
        self.saveButton.clicked.connect(addMovieDialog.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(addMovieDialog)

    def retranslateUi(self, addMovieDialog):
        _translate = QtCore.QCoreApplication.translate
        addMovieDialog.setWindowTitle(_translate("addMovieDialog", "Dialog"))
        self.filePathLineEdit.setPlaceholderText(_translate("addMovieDialog", "Select a file..."))
        self.browseButton.setText(_translate("addMovieDialog", "Browse..."))
        self.imdbidLabel.setText(_translate("addMovieDialog", "IMDB ID:"))
        self.checkIdButton.setText(_translate("addMovieDialog", "Check ID"))
        self.saveButton.setText(_translate("addMovieDialog", "Save"))
        self.cancelButton.setText(_translate("addMovieDialog", "Cancel"))
