# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'options_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OptionsDialog(object):
    def setupUi(self, OptionsDialog):
        OptionsDialog.setObjectName("OptionsDialog")
        OptionsDialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(OptionsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainTabWidget = QtWidgets.QTabWidget(OptionsDialog)
        self.mainTabWidget.setObjectName("mainTabWidget")
        self.generalSettingsTab = QtWidgets.QWidget()
        self.generalSettingsTab.setObjectName("generalSettingsTab")
        self.widget = QtWidgets.QWidget(self.generalSettingsTab)
        self.widget.setGeometry(QtCore.QRect(70, 50, 88, 22))
        self.widget.setObjectName("widget")
        self.maxthreadsBoxLayout = QtWidgets.QHBoxLayout(self.widget)
        self.maxthreadsBoxLayout.setContentsMargins(0, 0, 0, 0)
        self.maxthreadsBoxLayout.setSpacing(10)
        self.maxthreadsBoxLayout.setObjectName("maxthreadsBoxLayout")
        self.maxThreadsLabel = QtWidgets.QLabel(self.widget)
        self.maxThreadsLabel.setObjectName("maxThreadsLabel")
        self.maxthreadsBoxLayout.addWidget(self.maxThreadsLabel)
        self.maxThreadsSpinBox = QtWidgets.QSpinBox(self.widget)
        self.maxThreadsSpinBox.setObjectName("maxThreadsSpinBox")
        self.maxthreadsBoxLayout.addWidget(self.maxThreadsSpinBox)
        self.mainTabWidget.addTab(self.generalSettingsTab, "")
        self.libraryFoldersTab = QtWidgets.QWidget()
        self.libraryFoldersTab.setObjectName("libraryFoldersTab")
        self.gridLayout = QtWidgets.QGridLayout(self.libraryFoldersTab)
        self.gridLayout.setHorizontalSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.addFolderButton = QtWidgets.QPushButton(self.libraryFoldersTab)
        self.addFolderButton.setMinimumSize(QtCore.QSize(23, 23))
        self.addFolderButton.setMaximumSize(QtCore.QSize(23, 23))
        self.addFolderButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/plus-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addFolderButton.setIcon(icon)
        self.addFolderButton.setObjectName("addFolderButton")
        self.gridLayout.addWidget(self.addFolderButton, 1, 0, 1, 1)
        self.deleteFolderButton = QtWidgets.QPushButton(self.libraryFoldersTab)
        self.deleteFolderButton.setMinimumSize(QtCore.QSize(23, 23))
        self.deleteFolderButton.setMaximumSize(QtCore.QSize(23, 23))
        self.deleteFolderButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icons/delete-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteFolderButton.setIcon(icon1)
        self.deleteFolderButton.setIconSize(QtCore.QSize(15, 15))
        self.deleteFolderButton.setObjectName("deleteFolderButton")
        self.gridLayout.addWidget(self.deleteFolderButton, 1, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(298, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 3)
        self.folderListWidget = QtWidgets.QListWidget(self.libraryFoldersTab)
        self.folderListWidget.setObjectName("folderListWidget")
        self.gridLayout.addWidget(self.folderListWidget, 0, 0, 1, 5)
        self.mainTabWidget.addTab(self.libraryFoldersTab, "")
        self.verticalLayout.addWidget(self.mainTabWidget)
        self.mainButtonBox = QtWidgets.QDialogButtonBox(OptionsDialog)
        self.mainButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.mainButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.RestoreDefaults|QtWidgets.QDialogButtonBox.Save)
        self.mainButtonBox.setObjectName("mainButtonBox")
        self.verticalLayout.addWidget(self.mainButtonBox)

        self.retranslateUi(OptionsDialog)
        self.mainTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(OptionsDialog)

    def retranslateUi(self, OptionsDialog):
        _translate = QtCore.QCoreApplication.translate
        OptionsDialog.setWindowTitle(_translate("OptionsDialog", "Dialog"))
        self.maxThreadsLabel.setText(_translate("OptionsDialog", "Threads:"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.generalSettingsTab), _translate("OptionsDialog", "General Settings"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.libraryFoldersTab), _translate("OptionsDialog", "Library Folders"))
